const LEVELS = [
  {
    date: '2022-02-05',
    title: 'El día de los 3 gatos',
    description: '',
    goal: 7,
    timeLimit: 30,
    shootingStarSpeed: 1.8,
    shootingStarInterval: 1800,
    maxActiveStars: 3,
    starMaxLife: 350,
  },
  {
    date: '2025-09-06',
    title: 'El día de la boda',
    description: '',
    goal: 7,
    timeLimit: 28,
    shootingStarSpeed: 2.2,
    shootingStarInterval: 1700,
    maxActiveStars: 3,
    starMaxLife: 330,
  },
  {
    date: '2026-01-03',
    title: 'El día del cumpleaños',
    description: '',
    goal: 7,
    timeLimit: 27,
    shootingStarSpeed: 2.6,
    shootingStarInterval: 1600,
    maxActiveStars: 3,
    starMaxLife: 310,
  },
  {
    date: '2026-01-10',
    title: 'El día del violín',
    description: '',
    goal: 7,
    timeLimit: 25,
    shootingStarSpeed: 3.0,
    shootingStarInterval: 1500,
    maxActiveStars: 3,
    starMaxLife: 280,
  },
  {
    date: '2026-01-11',
    title: 'El día cósmico',
    description: '',
    goal: 7,
    timeLimit: 23,
    shootingStarSpeed: 3.4,
    shootingStarInterval: 1400,
    maxActiveStars: 3,
    starMaxLife: 260,
  },
  {
    date: '2026-01-31',
    title: 'El día del robo',
    description: '',
    goal: 7,
    timeLimit: 21,
    shootingStarSpeed: 3.8,
    shootingStarInterval: 1300,
    maxActiveStars: 3,
    starMaxLife: 240,
  },
  {
    date: '2026-02-14',
    title: 'El día de la memoria',
    description: '',
    goal: 7,
    timeLimit: 19,
    shootingStarSpeed: 4.2,
    shootingStarInterval: 1200,
    maxActiveStars: 3,
    starMaxLife: 220,
  },
  {
    date: '2026-03-15',
    title: 'El día del bloqueo',
    description: '',
    goal: 7,
    timeLimit: 17,
    shootingStarSpeed: 4.6,
    shootingStarInterval: 1100,
    maxActiveStars: 3,
    starMaxLife: 200,
  },
  {
    date: '2026-03-28',
    title: 'El día de la tv',
    description: '',
    goal: 7,
    timeLimit: 16,
    shootingStarSpeed: 5.0,
    shootingStarInterval: 1000,
    maxActiveStars: 3,
    starMaxLife: 180,
  },
  {
    date: '2026-04-03',
    title: 'El día de la aventura',
    description: '',
    goal: 7,
    timeLimit: 15,
    shootingStarSpeed: 5.5,
    shootingStarInterval: 900,
    maxActiveStars: 3,
    starMaxLife: 160,
    isFinalLevel: true,
  },
];

function formatDateSpanish(dateStr) {
  const months = [
    'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
    'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'
  ];
  const [year, month, day] = dateStr.split('-').map(Number);
  return `${day} de ${months[month - 1]} de ${year}`;
}
