const LEVELS = [
  {
    date: '2022-02-05',
    title: 'El día de los 3 gatos',
    description: '',
    completionText: 'Se vale decir que Dios hizo que el Erick se drogara ese dia? Suena raro pero no encuentro otra forma de explicarlo. No era el momento y Dios lo sabia...',
    goal: 7,
    timeLimit: 30,
    shootingStarSpeed: 1.8,
    shootingStarInterval: 1800,
    maxActiveStars: 3,
    starMaxLife: 350,
  },
  {
    date: '2025-09-06',
    title: 'El día de la boda',
    description: '',
    completionText: 'Tres años sin hablar y lo único que nos dijimos fue \'hola\' y una charla muy breve. Muy elocuentes los dos. Pero bueno, al menos esta vez no tuve que salir corriendo a rescatar a nadie.',
    goal: 7,
    timeLimit: 28,
    shootingStarSpeed: 2.2,
    shootingStarInterval: 1700,
    maxActiveStars: 3,
    starMaxLife: 330,
  },
  {
    date: '2026-01-03',
    title: 'El día del cumpleaños',
    description: '',
    completionText: 'Las coincidencias de la vida. Los dos habíamos estado en el mismo viaje espiritual por separado. Como si el universo nos hubiera dejado tarea en 2022 y los dos la hubiéramos hecho sin saber que había examen de recuperación.',
    goal: 7,
    timeLimit: 27,
    shootingStarSpeed: 2.6,
    shootingStarInterval: 1600,
    maxActiveStars: 3,
    starMaxLife: 310,
  },
  {
    date: '2026-01-10',
    title: 'El día del violín',
    description: '',
    completionText: 'La computadora se congeló, los actores hicieron una improvisacion cuestionable, y justo en el momento más incómodo de la noche... el violín más triste del mundo decidio que era momento de sonar. Fui a ver una obra, pero terminé viviendo una. Ni Godard lo hubiera escrito tan bien.',
    goal: 7,
    timeLimit: 25,
    shootingStarSpeed: 3.0,
    shootingStarInterval: 1500,
    maxActiveStars: 3,
    starMaxLife: 280,
  },
  {
    date: '2026-01-11',
    title: 'El día cósmico',
    description: '',
    completionText: '2 a.m. en un McDonald\'s. Cero estrellas, cero romanticismo, cien por ciento de papas fritas. Nuestro primer beso no fue bajo la luna, fue bajo los arcos dorados. Y honestamente, no lo cambiaría por nada.',
    goal: 7,
    timeLimit: 23,
    shootingStarSpeed: 3.4,
    shootingStarInterval: 1400,
    maxActiveStars: 3,
    starMaxLife: 260,
  },
  {
    date: '2026-01-31',
    title: 'El día del robo',
    description: '',
    completionText: 'Que bueno que ese dia no me robaste el carro pero, de todas formas, ya me habias robado algo mas importante.',
    goal: 7,
    timeLimit: 21,
    shootingStarSpeed: 3.8,
    shootingStarInterval: 1300,
    maxActiveStars: 3,
    starMaxLife: 240,
  },
  {
    date: '2026-02-14',
    title: 'El día de la memoria',
    description: '',
    completionText: 'Uns USB con fotos editadas por la IA y una playlist con nuestras canciones. Suena nerd. Fue nerd. Pero fue el mejor San Valentín que he tenido, así que el nerd ganó.',
    goal: 7,
    timeLimit: 19,
    shootingStarSpeed: 4.2,
    shootingStarInterval: 1200,
    maxActiveStars: 3,
    starMaxLife: 220,
  },
  {
    date: '2026-03-15',
    title: 'El día del bloqueo',
    description: '',
    completionText: 'Supongo que toda histora debe tener momentos tristes y complicados. A veces hay que hacer cortocircuito para que la conexión vuelva más fuerte. Perdon por ser un idiota, pero gracias por confrontarme. Fue muy necesario.',
    goal: 7,
    timeLimit: 17,
    shootingStarSpeed: 4.6,
    shootingStarInterval: 1100,
    maxActiveStars: 3,
    starMaxLife: 200,
  },
  {
    date: '2026-03-28',
    title: 'El día de la tv',
    description: '',
    completionText: 'Compramos una TV, comimos Encebollado, y respiramos el aire del sur. Todo maravilloso. Ese día el universo claramente estaba de buen humor, y nosotros también.',
    goal: 7,
    timeLimit: 16,
    shootingStarSpeed: 5.0,
    shootingStarInterval: 1000,
    maxActiveStars: 3,
    starMaxLife: 180,
  },
  {
    date: '2026-04-03',
    title: 'El día de la aventura',
    description: '',
    completionText: 'Si llegaste hasta aquí, ya sabes que esta aventura es impredecible. Y eso es lo mejor de todo, mientras sea contigo, todo estara bien. Te amo mi amor <3',
    goal: 7,
    timeLimit: 15,
    shootingStarSpeed: 5.5,
    shootingStarInterval: 900,
    maxActiveStars: 3,
    starMaxLife: 160,
    isFinalLevel: true,
  },
];

function formatDateSpanish(dateStr) {
  const months = [
    'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
    'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'
  ];
  const [year, month, day] = dateStr.split('-').map(Number);
  return `${day} de ${months[month - 1]} de ${year}`;
}
